spring:
  application:
    name: gateway
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

zuul:
  routes:
    baseServer: /baseServer/**
    ucServer: /uc/**
