server:
  port: 8082

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 5

spring:
  application:
    name: baseServer
  devtools:
      restart:
        enabled: true     #这里是为了热部署的，与mybatis是无关的

  #DATABASE CONFIG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/athena?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
#mybatis
mybatis:
  #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  mapper-locations: classpath*:/com/tangjing/athena/baseServer/dao/mapper/**Mapper.xml
  #这里是实体类的位置 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tangjing.athena.baseServer.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging
logging:
  level: warn